name: Your New Jekyll Site
#markdown: redcarpet
highlighter: rouge # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

#This is ugly... Is not working as the docomentatios says. This is the only way :(
#########################
# Navbar
#########################
navbar_home_link:
  esp: /inicio.html
  eng: /index.html
navbar_home_string:
  esp: Inicio
  eng: Index

navbar_games_link:
  esp: /juegos.html
  eng: /games.html
navbar_games_string:
  esp: Juegos
  eng: games

#########################
# Index: first box
#########################
index_first_box_title:
  esp: título
  eng: The title rocks

index_first_box_desc:
  esp: Esto es la descripcion de la caja
  eng: This is the description of the BOX

#########################
# Index: second box
#########################
index_second_box_title:
  esp: título
  eng: The title rocks

index_second_box_desc:
  esp: Esto es la descripcion de la caja
  eng: This is the description of the BOX

#########################
# Index: third box
#########################
index_third_box_title:
  esp: título
  eng: The title rocks

index_third_box_desc:
  esp: Esto es la descripcion de la caja
  eng: This is the description of the BOX

---
#layout: default
comments: true
# Disqus config
---

